---
- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Including Secret env
    include_vars:
     file: secrets.yml
     name: secret
  - name: reading VMs informations
    include_vars:
     file: servers.yml
     name: servers
  - name: Clone a VM from Template and customize
    vmware_guest:
     hostname: "{{secret.hostname}}"
     username: "{{secret.username}}"
     password: "{{secret.password}}"
     validate_certs: no
     datacenter: "{{ item.value.datacenter }}"
     cluster: "{{ item.value.cluster }}"
     name: "{{ item.value.name }}"
     template: "{{ item.value.template_name }}"
     datastore: "{{ item.value.date_store_name }}"
     annotation: "{{ item.value.note }}"
     customization:
       dns_servers:
        - "{{ item.value.dns1}}"
        - "{{ item.value.dns2}}" 
     networks:
     - name: "VM Network"
       ip: "{{ item.value.ip }}"
       netmask: "{{ item.value.netmask }}"
       gateway: "{{ item.value.gateway }}"
       dns_servers:
       - "{{ item.value.dns1}}"
       - "{{ item.value.dns2}}"
       vlan: "{{ item.value.vlan }}"
       device_type: vmxnet3
       type: static
       start_connected: yes
       connected: yes
       wait_for_ip_address: yes
     hardware:
       memory_mb: "{{ item.value.memory_gb * 1024 }}"
       num_cpus: "{{ item.value.cpu }}"
       hotadd_cpu: yes
       hotadd_memory: yes
       hotremove_cpu: yes
     state: poweredon
     folder: "{{ item.value.folder }}"
    loop: "{{ servers.vms | dict2items }}"
